### PR TITLE
Show UI helpers

### LINKED ISSUE #11: UI Assistance
See game requirements doc for details

@HMSimmonds @ParkerDW 

**Flood fill move**
- [x] Front-end
- [x] Back-end

**List of unit that are .ReadyForOrders**
- [ ] Front-end
- [x] Back-end

**Idem for villages**
- [ ] Front-end
- [x] Back-end

### PR DESCRIPTION
**Pull request by danhp**
Closes #11 once done

### CODE REVIEW

**Comment by justindomingue** [comment]
I see you remove the unit/village from the list after getting it? I don't think you put it back if it's not used right? (might be wiser to not move it to the end of the list?)

**Comment by danhp** [comment]
There's an append on the line right after...

**Comment by justindomingue** [comment]
Haha ok my bad! I'm on my iPad and github is not very responsive and I switched to this tab as soon as I read that line :0

**Comment by danhp** [comment]
:smile:  happens to the best of us

**Comment by justindomingue** [comment]
(not the best place to talk about this but I'm too lazy to text you with my phone) where do you handle canon firing? As per the rule, a canon should be able to fire within two hexagon range at a cost of 1 wood.

**Comment by justindomingue** [comment]
And thanks for making the ui helpers!

**Pull request merged**
